// handwritten
PN.page('mobile', {
  title: 'Mobile Components', icon: 'smartphone', nav: 'mobile',
  render() {
    const col = (label, inner) => `<div class="ds-demo" style="width:390px;flex:0 0 auto"><div class="ds-label">${label}</div>${inner}</div>`;
    const phoneA = M.phone({ nav: 'home', caption: 'Chrome: status bar · header · bottom nav', header: M.top({ brand: true, right: M.sync('ok', 'Synced') }), body:
      M.card('<div class="row between">' + C.eyebrow('Project') + M.tracking(true) + '</div><div class="m-card-title">Offshore Survey Alpha</div><div class="m-caption">Survey Engineer · MV Pageo 02</div>' + M.kv([['Started', '08:03'], ['Last sync', 'Now']]) + M.btn('View project', 'secondary', 'arrowright', 'project.html')) +
      M.card(C.eyebrow('Current status') + '<div class="m-status-big ok">On operation</div>' + M.kv([['GPS', 'Good · ± 7 m', 'ok'], ['Battery', '82%']]) + M.btnRow([M.btn('Check in', 'dark', 'pin', 'check-in.html'), M.btn('Scan', 'secondary', 'scanline', 'scan.html')])) +
      M.section('Today', 'All activity', 'activity.html') + M.card(M.timeline(window.DATA.me.today.slice(0, 3)), '', 'padding:16px 16px 12px') });
    const phoneB = M.phone({ nav: 'none', caption: 'Emergency template', banner: M.banner('crit', 'Emergency muster · MV Pageo 02'), center: true, body:
      M.ring('crit', 'flag') + '<div class="eyebrow crit">Muster requested</div><div class="m-h1">Proceed to Muster Point B</div>' + M.card(M.kv([['Location', 'Deck 2 · Starboard'], ['Distance', '180 m'], ['Requested', '15:38 by QHSE']]), '', 'width:100%') + M.btn("I'M SAFE", 'success lg', 'check') + M.btn('I need help', 'tertiary', null, 'sos.html', 'style="color:var(--s-crit)"') });
    return `
      <div class="ds-hero">${C.eyebrow('04 · Mobile components')}<h1>Act &amp; confirm, with gloves on.</h1><p>The mobile field app is not a miniature dashboard. Every control is at least 44 px, primary buttons are 54 px, body text is 16 px, and the tracking state is visible on every screen. Emergency screens are the only place strong color fills a surface.</p></div>

      <section class="ds-section" id="chrome">
        <div class="ds-head"><span class="no">4.1</span><h2>Frame, navigation &amp; templates</h2><p>390 × 844 · bottom navigation Home · Project · Map · Activity · Profile · SOS in the header only</p></div>
        <div class="stage" style="justify-content:flex-start">${phoneA}${phoneB}
          <div class="stack s16" style="width:360px">
            ${C.card({ title: 'Bottom navigation', body: '<div class="t-caption">Five destinations, 24 px icons, 11 px labels, active item gets an Ocean tint pill. SOS is deliberately not a destination — it lives in the header of every screen and requires a 2-second hold.</div><div class="m-nav" style="border:1px solid var(--border);border-radius:16px;height:auto;padding:8px 10px 10px">' + PN.mobileNav.map((n, i) => '<a href="#" class="' + (i === 0 ? 'active' : '') + '">' + C.icon(n.icon) + n.label + '</a>').join('') + '</div>' })}
            ${C.card({ title: 'Header variants', body: '<div class="stack s8"><header class="m-top" style="padding:0"><span class="brand" data-logo></span><span class="grow"></span>' + M.sync('ok', 'Synced') + '<span class="m-sos-btn">SOS</span></header><header class="m-top" style="padding:0"><span class="back">' + C.icon('arrowleft') + '</span><div class="m-title"><small>Asset</small>MBES-03</div><span class="m-sos-btn">SOS</span></header><header class="m-top" style="padding:0"><span class="back">' + C.icon('x') + '</span><div class="m-title">Scan asset</div></header></div>' })}
            ${C.card({ title: 'Mobile templates', body: C.kv([['Operational home', 'Identity → Project → Tracking → Status → Activity'], ['Checklist', 'Progress → Items → Scan → Confirm'], ['Map', 'Map → Current position → Objects → Bottom sheet'], ['Emergency', 'Critical message → Instruction → Primary action → Secondary info']], { stack: true }) })}
          </div>
        </div>
      </section>

      <section class="ds-section" id="primitives">
        <div class="ds-head"><span class="no">4.2</span><h2>Primitives</h2><p>Buttons · inputs · lists · key/value · chips · pills</p></div>
        <div class="row top wrap s16" style="align-items:flex-start">
          ${col('Buttons — 54 px, 64 px emergency', '<div class="stack s8">' + M.btn('Primary — Start operation', 'primary', 'play') + M.btn('Secondary — View project', 'secondary', 'arrowright') + M.btn('Dark — Check in', 'dark', 'pin') + M.btn('Destructive — Report issue', 'destructive', 'warning') + M.btn('Solid destructive — Call emergency contact', 'destructive solid', 'phone') + M.btn("Success — I'M SAFE", 'success lg', 'check') + M.btn('Tertiary — Learn how tracking works', 'tertiary', 'book') + M.btn('Disabled', 'primary disabled') + M.btnRow([M.btn('Cancel', 'secondary'), M.btn('Confirm', 'primary')]) + '</div>')}
          ${col('Inputs — 54 px, error with message', '<div class="stack s12">' + M.input({ label: 'Employee ID', value: 'PG-0142', icon: 'user' }) + M.input({ label: 'Password', value: '••••••••', icon: 'lock', type: 'password' }) + M.input({ label: 'Asset serial number', value: 'SN-02381920', help: 'Helper message' }) + M.input({ label: 'Asset serial number', value: 'SN-02381920', error: 'Serial number already registered.' }) + '<div class="m-input" style="height:auto;min-height:100px;align-items:flex-start;padding:12px 14px;color:var(--text-2)">Describe the issue…</div></div>')}
          ${col('Lists — 60 px rows', M.list([{ state: 'ok', title: 'MBES-03', sub: 'Multibeam Echo Sounder · Deployed', chev: true, href: '#' }, { state: 'ok', title: 'GPS-14', sub: 'GNSS Receiver · Deployed', chev: true, href: '#' }, { state: 'warn', title: 'Radio-021', sub: 'Not scanned today', right: '!' }, { state: 'pending', title: 'Battery Pack-04', sub: 'Pending' }]) + '<div style="height:12px"></div>' + M.list([{ icon: 'battery', iconCls: 'accent', title: 'Battery', right: '82%' }, { icon: 'locate', iconCls: 'accent', title: 'GPS', right: 'Good · ± 7 m' }, { avatar: 'AP', title: 'Andi Pratama', sub: 'Surveyor', right: M.chip('active', 'On vessel') }, { icon: 'logout', iconCls: 'crit', title: '<span class="crit">Sign out</span>' }]))}
          ${col('Key/value, chips, tracking pill', M.card(C.eyebrow('Current status') + '<div class="m-status-big ok">On vessel</div>' + M.kv([['Vessel', 'MV Pageo 02'], ['Boarded', '11:20'], ['Muster point', 'B · Deck 2']])) + '<div class="row s8 wrap">' + M.chip('active', 'Live · 12 s') + M.chip('info', 'Project Alpha') + M.chip('warn', '± 32 m', 'warning') + M.chip('crit', 'SOS') + M.chip('off', 'Pending sync') + M.chip('', 'Work area') + '</div><div class="row s8 wrap">' + M.tracking(true) + M.tracking(false) + '</div>' + '<div class="row s8 wrap">' + M.sync('ok', 'Synced') + M.sync('busy', 'Syncing') + M.sync('pending', 'Offline · 7 pending') + '</div>')}
          ${col('Cards, big numbers, progress', M.card(C.eyebrow('Equipment checklist') + M.bigNum(24, '/ 26 ready') + M.progress(92, 'warn') + '<div class="row s16 m-caption tnum"><span>Ready <b>24</b></span><span>Attention <b>1</b></span><span>Pending <b>1</b></span></div>') + M.card('<div class="row s12">' + C.icon('info', 'ic-24') + '<div><div class="m-label">Will sync when connection is available</div><div class="m-caption">Check-ins are stored locally on this device.</div></div></div>', 'tinted') + M.card(C.eyebrow('Team') + '<div class="row between"><span class="m-h3">12 personnel</span><span class="m-caption">10 accounted · 2 offline</span></div>' + M.progress(83, 'ok') + '<div class="m-avatar-row">' + ['FS', 'AP', 'RH', 'PA', 'DP', '+7'].map(a => C.avatar(a, a[0] === '+' ? 'dark' : '')).join('') + '</div>'))}
          ${col('Banners, rings, sheet', '<div class="stack s12">' + M.banner('offline', 'Offline', '7 events stored locally') + M.banner('crit', 'Emergency muster · MV Pageo 02') + '<div class="row s16" style="justify-content:center">' + M.ring('info', 'nfc', true) + M.ring('ok', 'check') + M.ring('warn', 'alert') + M.ring('crit', 'siren') + '</div><div style="position:relative;height:190px;border-radius:16px;overflow:hidden;background:var(--map-sea)">' + M.sheet(C.eyebrow('Your position') + '<div class="m-h3 tnum">-6.18746, 106.82721</div><div class="m-caption">Accuracy ± 7 m · Updated now</div><div class="row s8">' + M.chip('info', 'Project Alpha') + M.chip('', 'MV Pageo 02') + '</div>') + '</div></div>')}
        </div>
      </section>

      <section class="ds-section" id="rules">
        <div class="ds-head"><span class="no">4.3</span><h2>Field rules</h2></div>
        <div class="do-dont">
          <div class="dd do"><span class="tag">${C.icon('checkcircle', 'ic-14')}Do</span><p>Show the tracking state on every screen and say when it started. Keep one primary action per screen. Store every check-in locally and show pending counts. Use ± metres for accuracy and a warn chip above 25 m. Make SOS a press-and-hold.</p></div>
          <div class="dd dont"><span class="tag">${C.icon('xcircle', 'ic-14')}Don't</span><p>Don’t track outside an operation. Don’t rely on text under 13 px for field information. Don’t put SOS in the bottom navigation. Don’t shrink desktop tables onto the phone. Don’t hide offline state behind a small icon — it is a banner.</p></div>
        </div>
      </section>`;
  }
});
